title: She Comes and Goes as She Pleases
author: Lina Shammas
email: lina.shammas04@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  What's Lina Thinking about...

# social links
instagram_username: lina.shammas # DO NOT include the @ character, or else the build will fail!
github_username:  lina-shammas # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima 
